### PR TITLE
dev: header skeleton created, styled, not tested

### PR DESCRIPTION
**Pull request by wangx6**
- this is skeleton branch. To make the it visible i put a border around. The border is not in the design. will remove it later.

### CODE REVIEW

**Review by kevindoyleie — COMMENTED** [review]
review complete

**Review by kevindoyleie — APPROVED** [review]
approved

**Review by mosabcdef — APPROVED** [review]
All looks good

**Review by ashishbharvirkar — APPROVED** [review]
looks good.

**Pull request merged**
